apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bigu-backend-pod
  name: bigu-backend-pod
spec:
  containers:
    - image: localhost/bigu:latest
      name: bigu-backend
      ports:
        - containerPort: 8080
          hostPort: 8080
    - image: docker.io/library/postgres:14
      name: bigu-db
      ports:
        - containerPort: 5432
          hostPort: 5432
      tty: true
      volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: 7c18ed6b14b730c8c4241548985ee386a3a7a10738ceac2d44c2da30a835d5b8-pvc
  volumes:
      - name: 7c18ed6b14b730c8c4241548985ee386a3a7a10738ceac2d44c2da30a835d5b8-pvc
        persistentVolumeClaim:
          claimName: 7c18ed6b14b730c8c4241548985ee386a3a7a10738ceac2d44c2da30a835d5b8