apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bigu-backend-pod
  name: bigu-backend-pod
spec:
  containers:
    - image: localhost/bigu-backend:latest
      name: bigu-backend
      ports:
        - containerPort: 8080
          hostPort: 8080
    - image: docker.io/library/postgres:14
      name: bigu-db
      ports:
        - containerPort: 5432
          hostPort: 5432
      tty: true
      volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: bigu-db-pvc
      env:
        - name: POSTGRES_DB
          value: bigu
        - name: POSTGRES_USER
          value: bigu
        - name: POSTGRES_PASSWORD
          value: bigu
    - image: localhost/bigu-keycloak:latest
      name: bigu-keycloak
      ports:
        - containerPort: 8080
          hostPort: 8081
      tty: true
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: bigu-db-pvc
    - image: docker.io/library/postgres:14
      name: bigu-keycloak-db
      ports:
        - containerPort: 5433
          hostPort: 5433
      tty: true
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: bigu-keycloak-db-pvc
      env:
        - name: PGPORT
          value: 5433
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: bigu
        - name: POSTGRES_PASSWORD
          value: bigu


  volumes:
      - name: bigu-db-pvc
        persistentVolumeClaim:
          claimName: bigu-db

      - name: bigu-keycloak-db-pvc
        persistentVolumeClaim:
          claimName: bigu-keycloak-db